trigger: none

pool: sirinewpool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
     provider: 'azurerm'
     command: 'init'
     backendServiceArm: 'meraprinciple'
     backendAzureRmStorageAccountName: 'sgtsaurabh'
     backendAzureRmContainerName: 'newcont'
     backendAzureRmKey: '.tfstate'

- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'meraprinciple'
- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'meraprinciple'