trigger:
  none

pool: sirinewpool


steps:
  - 

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'meraprinciple'
    backendAzureRmStorageAccountName: 'deekshasa'
    backendAzureRmContainerName: 'deeksha-con'
    backendAzureRmKey: 'siri.tfstate'


